### ISSUE TITLE
SD DDP prevents a real physical DDP drive connected in second port to function

### ISSUE THREAD

**Issue by JohnLundy** [epearsoe/Coleco-ADAM-SD-DDP#1]
SD DDP prevents a real physical DDP drive connected in second port to function. Real DDP drive is recognized but when used it will start to spin forward at slow speed and until the end of tape is reached, followed by high speed rewind and repeats this over and over. The console needs to be powered down in order to get the drive to ever stop.

Troubleshooting done to determine this. Two physical DDP drives tested in second port would not function. It was found that removing the SD DDP will allow both physical DDP drives to function perfectly.

**Comment by epearsoe** [comment]
Investigating this issue. The latest version of the code should prevent the SD DDP (as drive 0) from moving if a physical DDP (as drive 1) is in motion. From looking at the Technical Manual and the schematics from the DDP drive this might require additional circuitry to fix and I would welcome comments. From the Tech Manual it says "STOP - Prevents tape motion and latches data drive output to Logic 1 when at Logic 1 (active high). Enables data drive output and tape motion when at Logic 0."  If you look at the DDP schematic it looks like when the signal for STOP if HIGH it activates a transistor Q3.  Right mid-section of schematic. I'm wondering if this transistor needs to be added to the Arduino DATA out line at pin 18. I've tried manipulating the port through software with no success.
[Schematic Read-Write (color).pdf](https://github.com/epearsoe/Coleco-ADAM-SD-DDP/files/4056436/Schematic.Read-Write.color.pdf)

**Comment by JohnLundy** [comment]
Taking a look at Q3, it appears to force the DATA OUT high when active. So, whenever STOP is low the DATA OUT is in a ‘normal’ state as Q3 is turned off. When STOP is not low, Q3 turns on holding the input of U2 (inverter) low, which causes the DATA OUT to be forced high the whole duration STOP is high.

STOP 0 = DATA OUT normal
STOP 1 = DATA OUT forced high

Seems like this should be able to be accomplished without the need of extra hardware.

**Comment by epearsoe** [comment]
You would think. I've tried bringing DATA OUT high on STOP but it didn't make any noticeable difference. If I start with DATA OUT as an INPUT, INPUT_PULLUP and set it that way on BRAKE OR STOP and set it to OUTPUT only when sending data I get a strange behavior.  Using File Manager If I access a physical DDP in drive 1 it will work fine. If I switch to the SD DDP in drive 0 I will get a 'Not an EOS Media'.  If I try again on the SD DDP it will work fine.  Then if I go back to physcial DDP I will get a "Not an EOS Media".  Then it will work fine.  Same happens in reverse.

**Comment by JohnLundy** [comment]
Version 1.3
 -  Changed virtual disk format from GW to HE which now allows for the SD DDP to work with a real DDP.
-  Successful block copy from real DDP with both left and center directory format to SD DDP
-  Added SN74LS7406N to ensure HI-Z state when SD DDP is stopped
